# Generated by Django 3.1.2 on 2022-04-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220403_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='tag', through='articles.Relationship', to='articles.Scorpe'),
        ),
    ]
