# Generated by Django 3.1.2 on 2022-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220405_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='scope', through='articles.Relationship', to='articles.Scorpe'),
        ),
    ]
