# Generated by Django 3.1.2 on 2022-04-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20220405_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='id_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.scorpe'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='id_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article'),
        ),
    ]
