# Generated by Django 3.1.2 on 2022-04-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20220405_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='id_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.article'),
        ),
    ]
