# Generated by Django 3.1.2 on 2022-04-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20220405_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='id_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.scorpe'),
        ),
    ]
