# Generated by Django 3.1.2 on 2022-04-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20220405_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='id_name',
            new_name='tag',
        ),
    ]
