# Generated by Django 3.1.2 on 2022-04-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20220405_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='tag',
            new_name='id_name',
        ),
    ]
