# Generated by Django 3.1.2 on 2022-04-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20220405_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['is_main']},
        ),
    ]
